[influx2]
    url = "http://pi-dev.local:8086"
    token = "super_secret_token"
    org = "my_org"
    timeout = 6000
    connection_pool_maxsize = 25
    # auth_basic = false
    # profilers="query, operator"
    # proxy = "http://proxy.domain.org:8080"

# [tags]
#     id = "123-456-789"
#     system = "development"

# [log]
#     level = "debug"
    # output = "stdout"
    # format = "logfmt"
    # color = true
    # pretty = true
    # file = "influx.log"
    # rotation_max_size = 10
    # rotation_max_age = "168h"
    # rotation_max_backups = 10
    # rotation_local_time = false
    # rotation_compress = false

[system]
    timezone = "America/Los_Angeles"