[influx2]
    url = "http://pi-monitor.local:8087"
    token = "super_secret_token"
    org = "my_org"
    timeout = 6000
    connection_pool_maxsize = 25
    auth_basic = false
    # profilers="query, operator"
    # proxy = "http://proxy.domain.org:8080"