[influx2]
url = "${INFLUXDB_URL}"
token = "${INFLUXDB_TOKEN}"
org = "${INFLUXDB_ORG}"
timeout = 20_000
connection_pool_maxsize = 25
auth_basic = false

[database_client.influx]
default_bucket = "testing"
default_write_precision = "s"
write_batch_size = 5_000
local_tz = "America/Vancouver"
